version: "3.7"

x-extractor-env: &extractor-env
  # General
  NAME: "icon-extractor"
  NETWORK_NAME: "mainnet"

  # Extractors
  START_CLAIM_EXTRACTORS: "true"
  NUM_CLAIM_EXTRACTORS: "4"
  MAX_CLAIM_SIZE: "1000"
  START_HEAD_EXTRACTOR: "false"
  HEAD_EXTRACTOR_START_BLOCK: "40000000"
  INSERT_EXTRACTOR_JOB: "true"
  INSERT_EXTRACTOR_JOB_START_BLOCK_NUMBER: "1"
  INSERT_EXTRACTOR_JOB_END_BLOCK_NUMBER: "10000000"

  # Logging
  LOG_LEVEL: "DEBUG"
  LOG_TO_FILE: "false"
  LOG_FILE_NAME: ""
  LOG_FORMAT: "console"
  LOG_IS_DEVELOPMENT: "true"

  # Kakfa
  KAFKA_BROKER_URL: "kafka:9092"

  # DB
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "changeme"
  DB_DBNAME: "postgres"
  DB_SSL_MODE: "disable"
  DB_TIMEZONE: "UTC"

services:
  extractor:
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    environment:
      <<: *extractor-env
