version: "3.7"

x-extractor-env: &extractor-env
  # General
  NAME: "icon-extractor"
  NETWORK_NAME: "mainnet"

  API_PORT: "${EXTRACTOR_API_PORT:-8000}"

  ICON_NODE_SERVICE_URL: "${ICON_NODE_SERVICE_URL:-https://api.icon.geometry.io/api/v3}"
  ICON_NODE_SERVICE_MAX_BATCH_SIZE: "${ICON_NODE_SERVICE_MAX_BATCH_SIZE:-100}"

  # Extractors
  START_CLAIM_EXTRACTORS: "false"
  NUM_CLAIM_EXTRACTORS: "4"
  MAX_CLAIM_SIZE: "1000"
  START_HEAD_EXTRACTOR: "true"
  HEAD_EXTRACTOR_START_BLOCK: "47132506"

  # Logging
  LOG_LEVEL: "DEBUG"
  LOG_TO_FILE: "false"
  LOG_FILE_NAME: ""
  LOG_FORMAT: "console"
  LOG_IS_DEVELOPMENT: "true"

  # Kakfa
  KAFKA_BROKER_URL: "kafka:9092"

  # DB
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "${DB_PASSWORD:-changeme}"
  DB_DBNAME: "postgres"
  DB_SSL_MODE: "disable"
  DB_TIMEZONE: "UTC"

services:
  extractor:
    build:
      context: ${EXTRACTOR_CONTEXT:-.}
      target: ${EXTRACTOR_TARGET:-prod}
#    ports:
#      - "8000:8000"
    environment:
      <<: *extractor-env
