definitions:
  routes.JobsBody:
    properties:
      end_block_number:
        type: integer
      start_block_number:
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample server server.
  title: Go api template docs
  version: "2.0"
paths:
  /api/v1/create-job:
    post:
      consumes:
      - '*/*'
      parameters:
      - description: '{}'
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/routes.JobsBody'
      produces:
      - application/json
      responses: {}
      summary: create an etl job
      tags:
      - Jobs
swagger: "2.0"
