info:
  contact: {}
  description: This is a sample server server.
  title: Go api template docs
  version: "2.0"
paths:
  /api/v1/create-job:
    post:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses: {}
      summary: create an etl job
      tags:
      - Jobs
swagger: "2.0"
