// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: block_etl.proto

package models

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *BlockETL) Validate() error {
	if !(this.Number > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Number", fmt.Errorf(`value '%v' must be greater than '0'`, this.Number))
	}
	for _, item := range this.Transactions {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Transactions", err)
			}
		}
	}
	return nil
}
func (this *TransactionETL) Validate() error {
	for _, item := range this.Logs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Logs", err)
			}
		}
	}
	return nil
}
func (this *LogETL) Validate() error {
	return nil
}
