// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: job.proto

package models

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Job) Validate() error {
	return nil
}
func (this *Claim) Validate() error {
	return nil
}
