// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: job.proto

package models

import (
	context "context"
	fmt "fmt"
	
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	math "math"

	gorm2 "github.com/infobloxopen/atlas-app-toolkit/gorm"
	errors1 "github.com/infobloxopen/protoc-gen-gorm/errors"
	gorm1 "github.com/jinzhu/gorm"
	field_mask1 "google.golang.org/genproto/protobuf/field_mask"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf

type JobORM struct {
	CreatedTimestamp int64
	EndBlockNumber   int64
	Hash             string `gorm:"primary_key"`
	IsHead           bool
	NumBatches       int64
	StartBlockNumber int64
}

// TableName overrides the default tablename generated by GORM
func (JobORM) TableName() string {
	return "jobs"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *Job) ToORM(ctx context.Context) (JobORM, error) {
	to := JobORM{}
	var err error
	if prehook, ok := interface{}(m).(JobWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Hash = m.Hash
	to.CreatedTimestamp = m.CreatedTimestamp
	to.StartBlockNumber = m.StartBlockNumber
	to.EndBlockNumber = m.EndBlockNumber
	to.IsHead = m.IsHead
	to.NumBatches = m.NumBatches
	if posthook, ok := interface{}(m).(JobWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *JobORM) ToPB(ctx context.Context) (Job, error) {
	to := Job{}
	var err error
	if prehook, ok := interface{}(m).(JobWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.Hash = m.Hash
	to.CreatedTimestamp = m.CreatedTimestamp
	to.StartBlockNumber = m.StartBlockNumber
	to.EndBlockNumber = m.EndBlockNumber
	to.IsHead = m.IsHead
	to.NumBatches = m.NumBatches
	if posthook, ok := interface{}(m).(JobWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type Job the arg will be the target, the caller the one being converted from

// JobBeforeToORM called before default ToORM code
type JobWithBeforeToORM interface {
	BeforeToORM(context.Context, *JobORM) error
}

// JobAfterToORM called after default ToORM code
type JobWithAfterToORM interface {
	AfterToORM(context.Context, *JobORM) error
}

// JobBeforeToPB called before default ToPB code
type JobWithBeforeToPB interface {
	BeforeToPB(context.Context, *Job) error
}

// JobAfterToPB called after default ToPB code
type JobWithAfterToPB interface {
	AfterToPB(context.Context, *Job) error
}

type BatchORM struct {
	BatchIndex       int64 `gorm:"primary_key"`
	EndBlockNumber   int64
	IsHead           bool
	JobHash          string `gorm:"primary_key"`
	StartBlockNumber int64
}

// TableName overrides the default tablename generated by GORM
func (BatchORM) TableName() string {
	return "batches"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *Batch) ToORM(ctx context.Context) (BatchORM, error) {
	to := BatchORM{}
	var err error
	if prehook, ok := interface{}(m).(BatchWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	to.JobHash = m.JobHash
	to.BatchIndex = m.BatchIndex
	to.StartBlockNumber = m.StartBlockNumber
	to.EndBlockNumber = m.EndBlockNumber
	to.IsHead = m.IsHead
	if posthook, ok := interface{}(m).(BatchWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *BatchORM) ToPB(ctx context.Context) (Batch, error) {
	to := Batch{}
	var err error
	if prehook, ok := interface{}(m).(BatchWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	to.JobHash = m.JobHash
	to.BatchIndex = m.BatchIndex
	to.StartBlockNumber = m.StartBlockNumber
	to.EndBlockNumber = m.EndBlockNumber
	to.IsHead = m.IsHead
	if posthook, ok := interface{}(m).(BatchWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type Batch the arg will be the target, the caller the one being converted from

// BatchBeforeToORM called before default ToORM code
type BatchWithBeforeToORM interface {
	BeforeToORM(context.Context, *BatchORM) error
}

// BatchAfterToORM called after default ToORM code
type BatchWithAfterToORM interface {
	AfterToORM(context.Context, *BatchORM) error
}

// BatchBeforeToPB called before default ToPB code
type BatchWithBeforeToPB interface {
	BeforeToPB(context.Context, *Batch) error
}

// BatchAfterToPB called after default ToPB code
type BatchWithAfterToPB interface {
	AfterToPB(context.Context, *Batch) error
}

// DefaultCreateJob executes a basic gorm create call
func DefaultCreateJob(ctx context.Context, in *Job, db *gorm1.DB) (*Job, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(JobORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(JobORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type JobORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type JobORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskJob patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskJob(ctx context.Context, patchee *Job, patcher *Job, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*Job, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"Hash" {
			patchee.Hash = patcher.Hash
			continue
		}
		if f == prefix+"CreatedTimestamp" {
			patchee.CreatedTimestamp = patcher.CreatedTimestamp
			continue
		}
		if f == prefix+"StartBlockNumber" {
			patchee.StartBlockNumber = patcher.StartBlockNumber
			continue
		}
		if f == prefix+"EndBlockNumber" {
			patchee.EndBlockNumber = patcher.EndBlockNumber
			continue
		}
		if f == prefix+"IsHead" {
			patchee.IsHead = patcher.IsHead
			continue
		}
		if f == prefix+"NumBatches" {
			patchee.NumBatches = patcher.NumBatches
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListJob executes a gorm list call
func DefaultListJob(ctx context.Context, db *gorm1.DB) ([]*Job, error) {
	in := Job{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(JobORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &JobORM{}, &Job{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(JobORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("hash")
	ormResponse := []JobORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(JobORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*Job{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type JobORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type JobORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type JobORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]JobORM) error
}

// DefaultCreateBatch executes a basic gorm create call
func DefaultCreateBatch(ctx context.Context, in *Batch, db *gorm1.DB) (*Batch, error) {
	if in == nil {
		return nil, errors1.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BatchORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BatchORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type BatchORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BatchORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm1.DB) error
}

// DefaultApplyFieldMaskBatch patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskBatch(ctx context.Context, patchee *Batch, patcher *Batch, updateMask *field_mask1.FieldMask, prefix string, db *gorm1.DB) (*Batch, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors1.NilArgumentError
	}
	var err error
	for _, f := range updateMask.Paths {
		if f == prefix+"JobHash" {
			patchee.JobHash = patcher.JobHash
			continue
		}
		if f == prefix+"BatchIndex" {
			patchee.BatchIndex = patcher.BatchIndex
			continue
		}
		if f == prefix+"StartBlockNumber" {
			patchee.StartBlockNumber = patcher.StartBlockNumber
			continue
		}
		if f == prefix+"EndBlockNumber" {
			patchee.EndBlockNumber = patcher.EndBlockNumber
			continue
		}
		if f == prefix+"IsHead" {
			patchee.IsHead = patcher.IsHead
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListBatch executes a gorm list call
func DefaultListBatch(ctx context.Context, db *gorm1.DB) ([]*Batch, error) {
	in := Batch{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BatchORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	db, err = gorm2.ApplyCollectionOperators(ctx, db, &BatchORM{}, &Batch{}, nil, nil, nil, nil)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BatchORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("job_hash")
	ormResponse := []BatchORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(BatchORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*Batch{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type BatchORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BatchORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm1.DB) (*gorm1.DB, error)
}
type BatchORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm1.DB, *[]BatchORM) error
}
