name: push-main-dockerhub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Go mod tidy
        run: cd src && go mod tidy

      - name: Bring up DBs
        run: make up-dbs

      - name: Check DBs
        run: make ps

      - name: Run tests
        run: cd src && go test ./... -v

      - name: Bring up stack
        run: make up && sleep 10

      - name: Check stack
        run: make ps

      - name: Go mod tidy
        run: cd tests && go mod tidy

      - name: Run tests
        run: cd tests && go test ./... -v

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: sudoblock/icon-go-etl

      - id: last
        uses: reloc8/action-latest-release-version@1.0.0

#      - id: last
#        uses: pozetroninc/github-action-get-latest-release@master
#        with:
#          repository: ${{ github.repository }}

      - name: Tag name
        id: source
        run: |
          echo ::set-output name=TAG::${{ steps.last.outputs.latest-release }}-${{ github.run_number }}

      - name: Build and push (API)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: prod
          push: true
          tags: sudoblock/icon-extractor:latest, sudoblock/icon-extractor:${{ steps.source.outputs.TAG }}

      - name: Checkout charts repo
        uses: actions/checkout@v2
        with:
          repository: sudoblockio/icon-charts
          ref: main
          path: charts
          token: ${{ secrets.ICON_CHARTS_PAT }}

      - name: Update dev-lax mainnet deployment values file (API)
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: sudoblockio/icon-charts
          valueFile: 'deployments/dev-lax/mainnet/extractor/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Configure credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.ICON_CHARTS_PAT }}'
          global: true

      - name: Commit all updates
        run: |
          git add -A
          git commit -m "extractor dev deployment image versions to ${{ steps.source.outputs.TAG }}"
          git push origin
        working-directory: charts
